### ISSUE TITLE
Efficient review score aggregation

### ISSUE THREAD

**Issue by brian-yu** [thecourseforum/theCourseForum2#11]
Some way of caching or precomputing aggregate review scores so that we don't have to recompute on every page load.

https://math.stackexchange.com/questions/106700/incremental-averageing

Prefetching

**Comment by j-alicia-long** [comment]
Proposal #1: Storing avg ratings in the Section model in avg_rating and update avg_rating on Review.save()
Would involve potentially creating new Section objects on review create

**Comment by j-alicia-long** [comment]
**Issue 2:** Some department pages take longer to load than others (ex. Curry School, Architecture School)
**Solution Proposal 2:**  Listing smaller schools' departments on the browse page via dropdown, split into smaller views, so they aren't all loaded on the school-department page
- Would involve turning the smaller schools' subdepartments (ex. Kinesiology) into departments
