### ISSUE TITLE
Add a JS linter and autoformatter (e.g. `eslint`).

### ISSUE THREAD

**Issue by brian-yu** [thecourseforum/theCourseForum2#113]
May be rendered unnecessary by superlinter

**Comment by j-alicia-long** [comment]
Closing this since the new github super linter incorporates JS linting w/ eslint (https://github.com/github/super-linter)

**Comment by j-alicia-long** [comment]
Never mind, it seems super-linter needs to be integrated with Github Actions

Though after digging around it may be good to replace Travis with Github Actions for performance improvements...

**Comment by Bartleby2718** [comment]
Resolved in #153
