### ISSUE TITLE
Simplify developer setup process

### ISSUE THREAD

**Issue by bradknaysi** [thecourseforum/theCourseForum2#119]
# Problem
There are hiccups in the current developer setup process (installing docker, cloning repo, loading database) particularly around the database setup. The biggest issue is having to run the `cat` command 3 times before the localhost database is complete.

- Docker install
- Cloning `theCourseForum2` repo
- Loading database

**Comment by alex-shen1** [comment]
Running `cat` 3 times is no longer necessary, and this issue is too vague to keep around
