### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by bradleyknaysi** [thecourseforum/theCourseForum2#134]
# Problem
If someone goes to a URL that doesn't exist, then the webpage crashes. We should have a dedicated tCF page for any un-matched URL path.

# Page Not Found currently
[https://prod.thecourseforum.com/this-page-does-not-exist](url)
<img width="465" alt="tCF page not found" src="https://user-images.githubusercontent.com/30380036/83336632-0f570c80-a283-11ea-8ffc-75c29b229276.png">

**Comment by akh4rf** [comment]
Issue #274 is more recent, closing issue.
