### ISSUE TITLE
AppRegistryNotReady: "Models aren't loaded yet."

### ISSUE THREAD

**Issue by bradknaysi** [thecourseforum/theCourseForum2#139]
# Problem
When running `docker-compose up`,  the following error is raised.

<img width="1235" alt="django error" src="https://user-images.githubusercontent.com/30380036/84581289-d607bc00-adad-11ea-98f9-013ef8d87c8b.png">

**Comment by bradknaysi** [comment]
I was able to fix the problem by first starting the database instance, then composing.

```
$ docker start tcf_db
$ docker-compose up
```

This implies that the `tcf_db` instance isn't finishing setup before it gets used by the `tcf_django` instance.

**Comment by bradknaysi** [comment]
After further investigation, I determined that the PR causing this bug was #122 (env security). 


## Error first appeared 😦 
```
$ git checkout dev
$ git reset --hard d618536 <---- (env security merged)
$ docker-compose up

...

tcf_django | django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.
```

## Commit before error appeared 😄 
```
$ git checkout dev
$ git reset --hard 83c9bcf <---- (login_redirect merged)
$ docker-compose up

...

tcf_django | Starting Django Server...
tcf_django | Watching for file changes with StatReloader
```

**Comment by j-alicia-long** [comment]
That was my PR - I'll look into it!
Sai and I had some trouble getting the env vars to work with Travis
TBH maybe if we switch to Github Actions we can circumvent a lot of these issues

**Comment by Bartleby2718** [comment]
@j-alicia-long I believe this was resolved?
