### ISSUE TITLE
Auto-deployment not working

### ISSUE THREAD

**Issue by bradknaysi** [thecourseforum/theCourseForum2#142]
# Problem
When changes get merged into the `dev` branch, it should automatically deploy those changes to `dev.thecourseforum.com`.

# Solution
I believe Brian used to host it on Heroku, and it needed to be transferred over to Jack. I'm not sure if Alex has it setup for auto-deployments.

**Comment by jackliu612** [comment]
This is outdated and has been resolved. Auto deployment are working and visible on dev.thecourseforum.com
