### ISSUE TITLE
Switch from Travis to GitHub Actions

### ISSUE THREAD

**Issue by alex-shen1** [thecourseforum/theCourseForum2#147]
- https://hacksoft.io/github-actions-in-action-setting-up-django-and-postgres/
- https://github.com/actions/starter-workflows/blob/main/ci/django.yml

**Comment by Bartleby2718** [comment]
@alex-shen1 I'm interested in working on this issue, but in what ways is GitHub Actions better than TravisCI?

**Comment by alex-shen1** [comment]
As far as I know, it's supposed to improve build times and allow us to use the oft-mentioned Super Linter. Also, native GitHub integration might be nice (to avoid having to click an extra external link), but that's a lesser concern. 

Obviously, it doesn't affect site functionality, so imo it should be a lower-priority issue for now, but if you're interested you can ask @j-alicia-long for more details.

**Comment by Bartleby2718** [comment]
Helpful links:
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions
https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables
https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads
https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls
https://birdie0.github.io/discord-webhooks-guide/discord_webhook.html
https://birdie0.github.io/discord-webhooks-guide/tools/curl.html
https://www.spycolor.com
