### ISSUE TITLE
auto-populate write a review form

### ISSUE THREAD

**Issue by vn6** [thecourseforum/theCourseForum2#156]
when clicking on write a review option on course page autofill known info:
- course prefix/number
- professor
- semester

**Comment by Bartleby2718** [comment]
This is great, but what if the course was offered a while ago? Right now, we don't allow writing reviews for old classes.

**Comment by j-alicia-long** [comment]
Hmm, good point. Maybe only have the button show if it was offered recently?

I guess you wouldn't populate semester automatically either
