### ISSUE TITLE
Deploy to Prod

### ISSUE THREAD

**Issue by brian-yu** [thecourseforum/theCourseForum2#19]
Finalize deployment strategy.

Requirements:
- Simple
- Auto-scaling
- Can handle Django app + elasticsearch

Nice to haves:
- scale to 0 
- auto-pull passing builds from master (Heroku-esque)
- all of our compute/storage is with one provider (to reduce knowledge fragmentation)
  - e.g. if DO, use DO managed DBs. If GCP, use CloudSQL, etc.

Candidates
- Google app engine (Brian's personal top pick)
- DO Droplets (as current)
- DO Kubernetes
- GCP Kubernetes
- AWS?

**Comment by bradknaysi** [comment]
# Update
We use Elastic to host our elasticsearch cluster. Costs ~$21 per month.

https://www.elastic.co/elasticsearch/service
