### ISSUE TITLE
Replace README with better content

### ISSUE THREAD

**Issue by j-alicia-long** [thecourseforum/theCourseForum2#216]
Current base readme is full of dev debugging documention
^ Move this to a separate markdown file

Add app summary & screenshots of app, such as https://github.com/thecourseforum/theCourseForum

**Comment by Bartleby2718** [comment]
^Closed this because it's a duplicate. Copied/pasted the content here:
> Current root directory readme is a giant wall of text. Consider adding screenshots of site pages to show state for current release version (launch upcoming), and also more helpful dev content (ex. debugging instructions, future plans, etc).

**Comment by alex-shen1** [comment]
We have a wiki now!
