### ISSUE TITLE
Some course pages are very slow

### ISSUE THREAD

**Issue by alex-shen1** [thecourseforum/theCourseForum2#247]
Example: ECON 2010 (http://127.0.0.1:8000/course/748)

Perhaps #242 (another performance improvement PR) holds a hint for how to fix this?

**Comment by Bartleby2718** [comment]
Check out https://thecourseforum-dev.herokuapp.com/course/748 now.
Seems like the PR you linked made it fast enough? 😉

**Comment by Bartleby2718** [comment]
Closing because the aforementioned PR resolved this issue.
