### ISSUE TITLE
Pretty 404 page

### ISSUE THREAD

**Issue by julesfll** [thecourseforum/theCourseForum2#274]
Bump of #134 

The current 404 page looks like this:
https://thecourseforum.com/this-page-does-not-exist
![image](https://user-images.githubusercontent.com/4724192/101143774-5f71ab80-35e5-11eb-9e1d-0828c2813941.png)

To do:
- Create 404/403/500 pages that looks better and provides more information to the user.
- Extend from `base.html` so navbar/sidebar are still present

**Comment by j-alicia-long** [comment]
Wait @julesfll were you working on this?
