### ISSUE TITLE
Multiple CourseInstructorGrade instances for a single (Course, Instructor) pair

### ISSUE THREAD

**Issue by Bartleby2718** [thecourseforum/theCourseForum2#293]
- Bug Report
  > - URL: https://thecourseforum.com/course/7421/3761
  > - Description: 
  > Hi! Are the grade distributions going to be fixed before course registration? Many classes that previously had the grade pie 
chart > filled in have not had it since the update. Thanks!
  > - Categories: [Data Error]
- Explanation
  - This is because a part of the current code assumes that `CourseInstructorGrade`  is unique for each (`Course`, `Instructor`) pair. It _should_ be, but it _currently is not_, because the underlying data is not so clean. Need to overhaul `loade_grades.py`.

**Comment by alex-shen1** [comment]
Also results in this error on prod for duplicate instances (i.e. John Hott for CS 2110):
![image](https://user-images.githubusercontent.com/55100084/101476614-0aeb6a80-391c-11eb-9953-162a4f51637c.png)

**Comment by alex-shen1** [comment]
@Bartleby2718 correct me if I'm wrong but I believe this issue is fixed by the merged PR; for the future, don't forget to add "Closes #{issue}" to initial PR descriptions so we can automatically close issues when they get merged

**Comment by Bartleby2718** [comment]
@alex-shen1 If I remember correctly, this issue was resolved temporarily, but there is no guarantee that this won't happen again. That's why I was hesitant to close this even though I knew I could close this using the keyword, but I guess we can keep it closed for now.
