### ISSUE TITLE
404 Not found when clicking privacy policy

### ISSUE THREAD

**Issue by joek13** [thecourseforum/theCourseForum2#360]
## Describe the bug
On the homepage FAQ, there is a link to the site privacy policy underneath "How do you protect reviewers' privacy?"

Clicking this link leads to a 404.

## To Reproduce
1. Go to [theCourseForum homepage](https://www.thecourseforum.com/)
2. Scroll down to FAQs
3. Click the "Privacy Policy" link
4. Observe the 404

## Expected behavior
I expect to see the site's privacy policy.

## Screenshots
![image](https://user-images.githubusercontent.com/2716970/105565917-391fe080-5cf7-11eb-95bb-373eb16e9164.png)

## Your Environment:
 - OS: Mac OSX
 - Browser: Brave (uses Chromium)

## Additional context
Using Chrome devtools, it looks like maybe the issue lies in the homepage template. 
![image](https://user-images.githubusercontent.com/2716970/105565946-6a001580-5cf7-11eb-98e1-571c5ca3f6db.png)
(Notice the `href` set to some unevaluated template logic)

**Comment by KartikChugh** [comment]
At first I thought the issue was the escape characters:

https://github.com/thecourseforum/theCourseForum2/blob/b839d7e4cb031a8654c1857a132e18b4ee96c345/tcf_website/views/_faqs.json#L32

Since they aren't used here:

https://github.com/thecourseforum/theCourseForum2/blob/4d665ce9e2d9c137560fba69b1a326e1f4e8df3b/tcf_website/templates/landing/landing.html#L322

But I see that they're used throughout the file for other links since it's JSON. So it looks instead like it's not possible to serve Django URL tags in this way. Maybe we could hardcode the /privacy URL if we don't expect that to change

**Comment by joek13** [comment]
> At first I thought the issue was the escape characters:
> 
> https://github.com/thecourseforum/theCourseForum2/blob/b839d7e4cb031a8654c1857a132e18b4ee96c345/tcf_website/views/_faqs.json#L32
> 
> Since they aren't used here:
> 
> https://github.com/thecourseforum/theCourseForum2/blob/4d665ce9e2d9c137560fba69b1a326e1f4e8df3b/tcf_website/templates/landing/landing.html#L322
> 
> But I see that they're used throughout the file for other links since it's JSON. So it looks instead like it's not possible to serve Django URL tags in this way. Maybe we could hardcode the /privacy URL if we don't expect that to change

@KartikChugh I haven't done a ton of research, but this might have something to do with how Django sanitizes inputs. Even though we know the JSON is safe, and there's no risk of an injection attack, django is sanitizing the template characters into plaintext.

**Comment by joek13** [comment]
Okay, actually, I think my last comment was a misunderstanding. Django template compilation happens before rendering, which means that if you put any template logic in the json (as we do for the privacy policy), it will never be executed.

One workaround would be to simply hardcode the URL. We could also consider writing the FAQs as their own template file (instead of JSON) and using an [include template tag](https://docs.djangoproject.com/en/3.1/ref/templates/builtins/#include) to reference it without bloating the landing page template.
