### ISSUE TITLE
Notification feature

### ISSUE THREAD

**Issue by alex-shen1** [thecourseforum/theCourseForum2#415]
**Describe the solution you'd like**
A notification button that shows various notifications.

**Describe alternatives you've considered**
Modals are a easier way to implement a similar feature, but have the downside of being more intrusive and non-personalizable. 

**Additional context**
Proposal [here](https://docs.google.com/presentation/d/1lTuTiClBFfQnKL0okLd7OGjzJbBMhIr6oX4PpVrZGtQ/edit#slide=id.gbec7c5d5ee_1_5).

**Comment by Bartleby2718** [comment]
Note to self:
- justification for `type` field in `Notification`: https://stackoverflow.com/questions/10515891/python-django-synonym-for-field-type-in-database-model-reserved-built-in-sym#comment58157992_10516154

**Comment by wkaisertexas** [comment]
I think this would be a decent idea, but we have not touched it in ~3 years. I am going to close this to prevent issue clutter. @barrett-ruth
