### ISSUE TITLE
Course enrollment data + viz

### ISSUE THREAD

**Issue by alex-shen1** [thecourseforum/theCourseForum2#416]
**Is your feature request related to a problem? Please describe.**
People would benefit from knowing the history of a course's enrollment, to both give them an idea of whether or not they'll get in, and a general heuristic for course difficulty (harder = more drop). We have some of this data from grades, but it's incomplete and Lou's has comprehensive data on all enrollment.

**Describe the solution you'd like**
We'd probably have to make new Model(s) for this - for example, grades data is represented by instances of `CourseInstructorGrade` (i.e. grades data on a given instructor-course combo), so we'd probably want something like `CourseInstructorEnrollment` to keep track of this in a similar way.

We'd also have to scrape Lou's in a new way we haven't done before and create a management command to load in new data, which might be a challenge.

**Additional context**
Beyond displaying the data on the site, we'll probably end up using this work as a baseline for some kind of waitlist predictor data project later, so it's going to be quite useful.

Proposal [here](https://docs.google.com/presentation/d/1lTuTiClBFfQnKL0okLd7OGjzJbBMhIr6oX4PpVrZGtQ/edit#slide=id.gbec7c5d5ee_7_0). Needs mockup!

**Comment by wkaisertexas** [comment]
@ajnye This was sort of the idea that I had for a tCF blog. However, I some of these more complex features (course builder, course visualizers, etc.) would benefit from a framework like React. Honestly, I think separation would just make things easier.
