### ISSUE TITLE
"All" tab on Course page should sort instructors by year

### ISSUE THREAD

**Issue by alex-shen1** [thecourseforum/theCourseForum2#424]
Ex: currently if you click All for CS 2110, the top listing is Mark Sherriff, who hasn't taught the class since 2012. This is pretty useless, so it'd be better to sort the instructors by recency.

![image](https://user-images.githubusercontent.com/55100084/110225204-0ef23e80-7eb1-11eb-9f37-9616555e51cb.png)

**Comment by Bartleby2718** [comment]
Sounds like an extension or a subtask of #264 to me?

**Comment by akh4rf** [comment]
Moved into issue #264.
