### ISSUE TITLE
Newlines are ignored in reviews

### ISSUE THREAD

**Issue by Bartleby2718** [thecourseforum/theCourseForum2#486]
## Describe the bug
No matter how many times you press "enter" in reviews, newlines are currently ignored.

## To Reproduce
1. Write a review that contains multiple consecutive newlines.
2. Submit the review.
3. Verify that the review doesn't seem to include any newlines, although the database does contain them.

## Expected behavior
Newlines should be visible.

## Screenshots
See the linked PR for this.

## Additional context
Solution: https://stackoverflow.com/questions/1356048/django-doesnt-display-newline-character-when-rendering-text-from-database

**Comment by alex-shen1** [comment]
Consensus from meeting: condense consecutive newline characters into one break
