### ISSUE TITLE
Search doesn't work on local?

### ISSUE THREAD

**Issue by alex-shen1** [thecourseforum/theCourseForum2#543]
Works on prod but not on my and @Ann924's machines (at least) for some reason

**Comment by ajnye** [comment]
<img width="1253" alt="Screen Shot 2022-01-30 at 2 54 20 PM" src="https://user-images.githubusercontent.com/52001765/151715301-755ec120-5d26-4acd-8325-22ce1d726584.png">
Using Django's superuser, the Subdepartments do not exist on the local side, causing a list index error..

**Comment by jackliu612** [comment]
New dump should work: [https://drive.google.com/file/d/1KEjCaIO5YvDCvLsrd3WImpLJmIE-jApC/view?usp=sharing](https://drive.google.com/file/d/1KEjCaIO5YvDCvLsrd3WImpLJmIE-jApC/view?usp=sharing)
