### ISSUE TITLE
Get Rid of Marketing Recruitment Banner

### ISSUE THREAD

**Issue by borjainglefernandez** [thecourseforum/theCourseForum2#549]
**Is your feature request related to a problem? Please describe.**
Get rid of this modal since the deadline has passed.

<img width="1380" alt="Screenshot 2021-11-14 at 2 34 32 PM" src="https://user-images.githubusercontent.com/65180311/141695831-d175dc74-d40d-4154-adf3-ec3e4f0000e8.png">

**Comment by alex-shen1** [comment]
Already done in #539

**Comment by alex-shen1** [comment]
lol oops, I linked the wrong PR, but if you check dev it is done already
