### ISSUE TITLE
Sidebar Review Button Behavior when Not Logged In

### ISSUE THREAD

**Issue by Ann924** [thecourseforum/theCourseForum2#698]
## Describe the bug
The sidebar review button does not do anything when the user is not logged into theCourseForum.

## To Reproduce
Steps to reproduce the behavior. For example:
1. Go to https://thecourseforum.com/about/
2. Click on Reviews on the sidebar
3. See how the page does not change for the user

## Expected behavior
When the user is not logged in and the user clicks on the 'Reviews' option on the sidebar, the UI should redirect to the login module.

## Screenshots

Current Behavior: Clicking on 'Reviews' on the sidebar doesn't produce any changes
![image](https://github.com/thecourseforum/theCourseForum2/assets/78228879/cfd5b4e1-1f8f-43d1-8539-269a76a9d38e)

Expected Behavior: Clicking on 'Reviews' should redirect to the login module
![image](https://github.com/thecourseforum/theCourseForum2/assets/78228879/ab5b2465-c2cc-4186-a781-0ddbb7915af8)

## Your Environment:
 - OS: [e.g. Windows 10, iOS, Linux]
 - Browser [e.g. Chrome, Safari, Firefox]

**Comment by arthurwu1227** [comment]
Hi Ann,

I would like to work on this issue.
