### ISSUE TITLE
When viewing “All” professors on course page, highlight most recent profs

### ISSUE THREAD

**Issue by j-alicia-long** [thecourseforum/theCourseForum2#72]

**Comment by brian-yu** [comment]
@alex-shen1 were you the one who came up with this idea? Can you elaborate on it? If not, do you remember who did?

**Comment by alex-shen1** [comment]
I'm not sure if I came up with it or someone else did, but I'm guessing the idea is that currently there's no distinction between professors who aren't teaching a class now but do regularly (e.g. non-Bloomfield profs for 2150) and professors who no longer teach the class, and there should be something marking the difference. Shouldn't be too hard to implement, so if nobody else wants to I can try picking it up after finals.

**Comment by alex-shen1** [comment]
Duplicated by #424
