### ISSUE TITLE
Docker Slow/Reinstalls Modules

### ISSUE THREAD

**Issue by ajnye** [thecourseforum/theCourseForum2#737]
## Describe the bug
Docker currently reinstalls modules with the same version even if they're already installed on docker-compose up, making it take longer than needed.

## To Reproduce
Run docker locally using docker-compose up and notice how many redundant modules are reinstalled.

## Your Environment:
 - OS: [e.g. Windows 10, iOS, Linux]
 - Browser [e.g. Chrome, Safari, Firefox]

**Comment by barrett-ruth** [comment]
done w/ #743
