### ISSUE TITLE
Better Search

### ISSUE THREAD

**Issue by brian-yu** [thecourseforum/theCourseForum2#75]
See #79 

Improve upon the website's search.

Ask @brian-yu if you have any questions

Done - Basic search functions

In progress 
- Fix weird results (instructors)
- Improve UI

**Comment by bradknaysi** [comment]
# Starting point... read the documentation!

[Elasticsearch Search API](https://swiftype.com/documentation/app-search/api/searchI)

**Comment by bradknaysi** [comment]
# Update
### Todo
- improve instructor search algorithm
     - add weights
     - add boost for professors with recently taught courses

**Comment by alex-shen1** [comment]
Too vague, if we revisit this at some point we'll make a new issue.
