### ISSUE TITLE
tCF - Rust Edition

### ISSUE THREAD

**Issue by wkaisertexas** [thecourseforum/theCourseForum2#816]
![image](https://github.com/thecourseforum/theCourseForum2/assets/27795014/0e39278b-75c1-427f-9ada-8682a5f33e2a)

> Note: this is a joke PR, don't ban me

**Comment by barrett-ruth** [comment]
bro... i wasnt serious 😭🍜

**Comment by wkaisertexas** [comment]
I was.

**Comment by wkaisertexas** [comment]
Actually not that serious
