### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by barrett-ruth** [thecourseforum/theCourseForum2#843]
# Refactoring

- Pagination - builtin Django (course reviews)
- Address all "TODO" comments
- Align text count bar on review page
- Backlog (github issues)
- Course Review UI ugly 
  - Centered items
  - Centered warnings
- Updating application with changes to `requirements.txt`
  
 Add any of your QOL refactors below.

**Comment by artiehumphreys** [comment]
- Move models out of QA and Profile
