### ISSUE TITLE
Computer Science isn't listed under E-School

### ISSUE THREAD

**Issue by bradknaysi** [thecourseforum/theCourseForum2#91]
CS isn't listed as a department under the E-School, only the College of Arts & Sciences

- look into input json from SIS or lou's list (ask brian)
- update data migration code to create an e-school model instance for CS

**Comment by j-alicia-long** [comment]
@bradknaysi should it be listed under just e-school, or both? (would have to redo some db models if we want cross-listing)
@brian-yu is CS both a department and a subdepartment?

**Comment by jackliu612** [comment]
There is also an 'UNKNOWN' category under Other Schools at the University of Virginia which seems to be a bug
